# Generated by Django 4.1.3 on 2023-03-27 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_image_movie_image_music_alter_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='image',
            name='music',
        ),
    ]
